import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { ProvideAuth } from '../lib/auth'
import { ThemeProvider } from '@chakra-ui/system'
import theme from '@chakra-ui/theme'
import Head from 'next/head'
import { ChakraProvider } from '@chakra-ui/react'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider>
      <ProvideAuth>
        <Head>
          <title>NextJs</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Component {...pageProps} />
      </ProvideAuth>
    </ChakraProvider>
  )
}
export default MyApp
