import '../styles/globals.scss'
import type { AppProps } from 'next/app'
import { ProvideAuth } from '../lib/auth'
import customTheme from '../styles/themes'
import Head from 'next/head'
import { ChakraProvider } from '@chakra-ui/react'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import useSWR, { SWRConfig } from 'swr'
function MyApp({ Component, pageProps }: AppProps) {

  const fetcher = (...args: any) => fetch(args).then(res => res.json())
  return (


    < ChakraProvider theme={customTheme} >
      <SWRConfig value={{ fetcher }}>
        <ProvideAuth>
          <Head>
            <title>BevanTony</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar />
          <Component {...pageProps} />
          <Footer />
        </ProvideAuth>
      </SWRConfig>
    </ChakraProvider>
  )
}
export default MyApp
