import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { ProvideAuth } from '../lib/auth'
import customTheme from '../styles/themes'
import Head from 'next/head'
import { ChakraProvider } from '@chakra-ui/react'
import Navbar from '../components/Navbar'

function MyApp({ Component, pageProps }: AppProps) {

  return (
    <ChakraProvider theme={customTheme}>
      <ProvideAuth>
        <Head>
          <title>BevanTony</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <Component {...pageProps} />
      </ProvideAuth>
    </ChakraProvider>
  )
}
export default MyApp
